# Setup
title: Sea of Tranquility
tagline: A blog
url: https://puttym.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

pages_list:
        About: '/about'
        Archive: '/archive'
        Feed: '/atom.xml'

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Madhukara Putty
  url: https://twitter.com/msputty26
  email: puttym@gmail.com

# Custom vars
version: 3.0.0
